# #####################################################################
# Automatically generated by qmake (2.01a) Mo 26. Okt 18:26:00 2009
# #####################################################################
TEMPLATE = app
TARGET = clipgrab
DEPENDPATH += . \
    release
INCLUDEPATH += .
QT += core \
    widgets
QT += gui
QT += network
QT += xml

# The port targets C++20 (matches CMakeLists); qmake defaults to C++17,
# under which the [=, this] lambda captures only warn but this keeps the
# two build systems consistent.
CONFIG += c++20

# NOTE: CMake (CMakeLists.txt) is the primary, CI-validated build system.
# This .pro is kept for convenience but is not exercised by CI, so it can
# drift — if it fails, prefer building with CMake.

# Input
HEADERS += converter.h \
    converter_copy.h \
    converter_ffmpeg.h \
    download_list_model.h \
    helper_downloader.h \
    mainwindow.h \
    video.h \
    notifications.h \
    message_dialog.h \
    clipgrab.h \
    youtube_dl.h
FORMS += metadata-dialog.ui \
    helper_downloader.ui \
    mainwindow.ui \
    update_message.ui \
    message_dialog.ui
SOURCES += converter.cpp \
    converter_copy.cpp \
    converter_ffmpeg.cpp \
    download_list_model.cpp \
    helper_downloader.cpp \
    main.cpp \
    mainwindow.cpp \
    video.cpp \
    notifications.cpp \
    message_dialog.cpp \
    clipgrab.cpp \
    youtube_dl.cpp
RESOURCES += resources.qrc
TRANSLATIONS += clipgrab_bg.ts \
                clipgrab_bn.ts \
                clipgrab_ca.ts \
                clipgrab_cs.ts \
                clipgrab_de.ts \
                clipgrab_el.ts \
                clipgrab_es.ts \
                clipgrab_eu.ts \
                clipgrab_fa.ts \
                clipgrab_fr.ts \
                clipgrab_fi.ts \
                clipgrab_hr.ts \
                clipgrab_hu.ts \
                clipgrab_id.ts \
                clipgrab_it.ts \
                clipgrab_ja.ts \
                clipgrab_ko.ts \
                clipgrab_mk.ts \
                clipgrab_lt.ts \
                clipgrab_nl.ts \
                clipgrab_no.ts \
                clipgrab_pa.ts \
                clipgrab_pl.ts \
                clipgrab_pt.ts \
                clipgrab_ro.ts \
                clipgrab_ru.ts \
                clipgrab_si.ts \
                clipgrab_sr.ts \
                clipgrab_sv.ts \
                clipgrab_sw.ts \
                clipgrab_tr.ts \
                clipgrab_vi.ts \
                clipgrab_zh.ts \
                clipgrab_strings.ts
CODECFORTR = UTF-8
win32:RC_FILE = windows_icon.rc
macx { 
    TARGET = ClipGrab
    ICON = clipgrab.icns
    RC_FILE = clipgrab.icns
    QMAKE_INFO_PLIST = ClipGrab.plist
    LIBS += -framework AppKit -framework Foundation
}
VERSION = 3.9.14
# Quote the value so the preprocessor sees a string literal — main.cpp does
# QStringLiteral(CLIPGRAB_VERSION). Without the escaped quotes qmake passes
# -DCLIPGRAB_VERSION=3.9.14 (bare), which breaks compilation.
DEFINES += CLIPGRAB_VERSION=\\\"$$VERSION\\\"
